// Taken from https://chancejs.com
const ANIMALS = [
  //list of ocean animals comes from https://owlcation.com/stem/list-of-ocean-animals
  "Acantharea","Anemone","Albacore","Anchovy","Barnacle","Barracuda","Baus","Bluefish","Clam","Cod","Coelacanth","Conch","Copepod","Coral","Corydoras","Crab","Cuttlefish","Dolphin","Dolphinfish","Dory","Dugong","Eel","Flameback","Flatfish","Flounder","Fluke","Gar","Geoduck","Goosefish","Grouper","Grunion","Haddock","Hake","Halibut","Hapuka","Hatchetfish","Herring","Hoki","Icefish","Isopod","Jellyfish","Krill","Lamprey","Limpet","Ling","Lionfish","Lobster","Manatee","Marlin","Mollusk","Monkfish","Mullet","Mussel","Megaladon","Narwhal","Nautilus","Needlefish","Nudibranch","Oarfish","Octopus","Ostracod","Otter","Oyster","Penguin","Pilchard","Pinniped","Plankton","Porpoise","Quahog","Ragfish","Ratfish","Ray","Sablefish","Salmon","Sawfish","Seahorse","Seal","Shark","Shrimp","Smelts","Sponge","Squid","Squidworm","Starfish","Stickleback","Stonefish","Sturgeon","Swordfish","Tilefish","Toadfish","Tuna","Viperfish","Vaquita","Wahoo","Walrus","Whale","Wobbegong","Wrasse","Wreckfish","Xiphosura","Zebrashark","Zooplankton",
  //list of desert, grassland, and forest animals comes from http://www.skyenimals.com/
  "Aardwolf","Addax","Ant","Antelope","Armadillo","Baboon","Badger","Bat","Beetle","Bird","Boa","Bustard","Butterfly","Camel","Caracal","Caracara","Caterpillar","Centipede","Cheetah","Chipmunk","Chuckwalla","Coati","Cobra","Cougar","Courser","Crow","Dove","Dunnart","Eagle","Echidna","Elephant","Emu","Falcon","Fly","Fox","Frogmouth","Gecko","Gerbil","Grasshopper","Guanaco","Gundi","Hamster","Hawk","Hedgehog","Hyena","Hyrax","Jackal","Kangaroo","Kestrel","Kowari","Kultarr","Leopard","Lion","Macaw","Meerkat","Mouse","Oryx","Ostrich","Owl","Pronghorn","Python","Rabbit","Raccoon","Rattlesnake","Rhinoceros","Starling","Tarantula","Toad","Tortoise","Viper","Vulture","Waxwing","Xerus","Zebra",
  "Aardvark","Aardwolf","Accentor","Alpaca","Anaconda","Ant","Anteater","Antelope","Armadillo","Baboon","Badger","Bandicoot","Barbet","Bat","Bee","Beetle","Bird","Bison","Bluebird","Boa","Bowerbird","Bushshrike","Bustard","Butterfly","Buzzard","Caracal","Caracara","Cardinal","Caterpillar","Cheetah","Chipmunk","Civet","Coati","Cobra","Cockatoo","Cockroach","Cougar","Courser","Coyote","Crane","Cricket","Crow","Culpeo","Deer","Dingo","Dinosaur","Dove","Drongo","Duck","Duiker","Dunnart","Eagle","Echidna","Elephant","Elk","Emu","Falcon","Finch","Flea","Fly","Fox","Frog","Frogmouth","Gazelle","Gecko","Gerbil","Giraffe","Grasshopper","Grison","Groundhog","Grouse","Guanaco","Hamster","Harrier","Hartebeest","Hawk","Hedgehog","Helmetshrike","Hippopotamus","Hornbill","Hyena","Hyrax","Impala","Jackal","Jaguar","Jaguarundi","Kangaroo","Kestrel","Kultarr","Ladybug","Leopard","Lion","Macaw","Meerkat","Mouse","Newt","Oryx","Ostrich","Owl","Pangolin","Pheasant","Pronghorn","Python","Quoll","Rabbit","Raven","Rhinoceros","Shelduck","Squirrel","Starling","Tamandua","Thornbill","Thrush","Toad","Tortoise",
  "Agouti","Anaconda","Anoa","Ant","Anteater","Antelope","Armadillo","Babirusa","Baboon","Badger","Bandicoot","Banteng","Barbet","Basilisk","Bat","Bee","Beetle","Bettong","Binturong","Bongo","Bowerbird","Bulbul","Bushbaby","Bushshrike","Butterfly","Buzzard","Caecilian","Cardinal","Cassowary","Caterpillar","Centipede","Chameleon","Chimpanzee","Cicada","Civet","Coati","Cobra","Cockatoo","Cockroach","Colugo","Cotinga","Cougar","Cricket","Crocodile","Crow","Cuckoo","Cuscus","Deer","Dhole","Dingo","Dinosaur","Drongo","Duck","Duiker","Eagle","Echidna","Elephant","Finch","Flea","Flowerpecker","Fly","Fossa","Frog","Frogmouth","Gaur","Gecko","Gorilla","Grison","Hawk","Hedgehog","Helmetshrike","Hornbill","Hyrax","Iguana","Jackal","Jaguar","Jaguarundi","Kestrel","Ladybug","Lemur","Leopard","Lion","Macaw","Mandrill","Margay","Monkey","Mouse","Newt","Okapi","Orangutan","Owl","Pangolin","Peafowl","Pheasant","Possum","Python","Quokka","Rabbit","Raccoon","Rhinoceros","Squirrel","Starling","Tamandua","Tamarin","Tapir","Tarantula","Thrush","Tiger","Toad","Tortoise","Toucan","Trogon","Trumpeter","Turaco","Turtle","Viper","Vulture","Wallaby","Warbler","Wasp","Waxwing","Weaver","Whistler","Whydah","Woodswallow","Worm","Wren","Xenops","Yellowjacket","Accentor","Anole","Bird","Bison","Boa","Chipmunk","Copperhead","Coyote","Dormouse","Elk","Emu","Fisher","Fox","Groundhog","Grouse","Guanaco","Kangaroo","Koala","Numbat","Quoll","Thornbill","Turkey","Vole","Weasel","Wildcat","Wolf","Wombat","Woodchuck","Woodpecker",
  //list of farm animals comes from https://www.buzzle.com/articles/farm-animals-list.html
  "Alpaca","Buffalo","Banteng","Cow","Cat","Chicken","Carp","Camel","Donkey","Dog","Duck","Emu","Goat","Gayal","Guinea","Goose","Horse","Honey","Llama","Pig","Pigeon","Rhea","Rabbit","Sheep","Silkworm","Turkey","Yak","Zebu",
  //list of pet animals comes from https://www.dogbreedinfo.com/pets/pet.htm
  "Bird","Burro","Cat","Chameleon","Chicken","Chinchilla","Cow","Dog","Donkey","Duck","Ferret","Fish","Gecko","Goose","Gerbil","Goat","Hamster","Hedgehog","Horse","Iguana","Llama","Lizard","Mice","Mule","Peafowl","Pigeon","Pony","Rabbit","Rat","Sheep","Skunk","Snake","Tarantula","Turkey","Turtle",
  //list of zoo animals comes from https://bronxzoo.com/animals
  "Aardvark","Anaconda","Chinchilla","Fossa","Gelada","Giraffe","Gorilla","Lion","Okapi","Zebra"
];

function randomAnimal() {
  const idx = Math.floor(Math.random() * ANIMALS.length);
  return ANIMALS[idx].toLowerCase();
}

module.exports = function() {
  return randomAnimal() + '_' + randomAnimal();
}

